name: country-info-app

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=country_app
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    container_name: country-info-app-database
    volumes:
      - country_info_app_dbdata:/var/lib/postgresql/data
    ports:
      - '9001:5432'
  
volumes:
  country_info_app_dbdata:

